version: '3.9'

services:
  app:
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./api/capstone-api/:/var/www/html
  
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./api/capstone-api/:/var/www/html
  
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: capstone
      MYSQL_USER: admin
      MYSQL_PASSWORD: abc123
      MYSQL_ROOT_PASSWORD: abc123
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume: